In [2]:
import pandas as pd

In [4]:
pd.read_csv('../test.csv')

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
5,1466,60,RL,75.0,10000,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
6,1467,20,RL,NaN,7980,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,GdPrv,Shed,500,3,2010,WD,Normal
7,1468,60,RL,63.0,8402,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
8,1469,20,RL,85.0,10176,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
9,1470,20,RL,70.0,8400,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,4,2010,WD,Normal
10,1471,120,RH,26.0,5858,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
11,1472,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,COD,Normal
12,1473,160,RM,21.0,1680,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2010,WD,Normal
13,1474,160,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
14,1475,120,RL,24.0,2280,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
15,1476,60,RL,102.0,12858,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,New,Partial
16,1477,20,RL,94.0,12883,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,New,Partial
17,1478,20,RL,90.0,11520,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
18,1479,20,RL,79.0,14122,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2010,WD,Normal
19,1480,20,RL,110.0,14300,Pave,NaN,Reg,HLS,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
20,1481,60,RL,105.0,13650,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
21,1482,120,RL,41.0,7132,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
22,1483,20,RL,100.0,18494,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,WD,Normal
23,1484,120,RL,43.0,3203,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,1,2010,WD,Normal
24,1485,80,RL,67.0,13300,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
25,1486,60,RL,63.0,8577,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
26,1487,60,RL,60.0,17433,Pave,NaN,IR2,Lvl,AllPub,...,256,0,NaN,NaN,NaN,0,1,2010,WD,Normal
27,1488,20,RL,73.0,8987,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal
28,1489,20,FV,92.0,9215,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2010,New,Partial
29,1490,20,FV,84.0,10440,Pave,NaN,Reg,Lvl,AllPub,...,216,0,NaN,NaN,NaN,0,5,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2890,30,RM,50.0,7030,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2006,WD,Normal
1430,2891,50,RM,75.0,9060,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1431,2892,30,C (all),69.0,12366,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1432,2893,190,C (all),50.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Abnorml
1433,2894,50,C (all),60.0,8520,Grvl,NaN,Reg,Bnk,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1434,2895,120,RM,41.0,5748,Pave,NaN,IR1,HLS,AllPub,...,153,0,NaN,NaN,NaN,0,2,2006,New,Partial
1435,2896,120,RM,44.0,3842,Pave,NaN,IR1,HLS,AllPub,...,155,0,NaN,NaN,NaN,0,12,2006,WD,Normal
1436,2897,20,RL,69.0,23580,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Normal
1437,2898,90,RL,65.0,8385,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1438,2899,20,RL,70.0,9116,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1439,2900,80,RL,140.0,11080,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1440,2901,20,RL,NaN,50102,Pave,NaN,IR1,Low,AllPub,...,138,0,NaN,NaN,NaN,0,3,2006,WD,Alloca
1441,2902,20,RL,NaN,8098,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1442,2903,20,RL,95.0,13618,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,New,Partial
1443,2904,20,RL,88.0,11577,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,New,Partial
1444,2905,20,NaN,125.0,31250,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1445,2906,90,RM,78.0,7020,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal
1446,2907,160,RM,41.0,2665,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1447,2908,20,RL,58.0,10172,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal
1448,2909,90,RL,NaN,11836,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,3,2006,WD,Normal
1449,2910,180,RM,21.0,1470,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Normal
1450,2911,160,RM,21.0,1484,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1451,2912,20,RL,80.0,13384,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2006,WD,Normal
1452,2913,160,RM,21.0,1533,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2006,WD,Abnorml
1453,2914,160,RM,21.0,1526,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,GdPrv,NaN,0,6,2006,WD,Normal
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [8]:
pd.read_table('http://bit.ly/movieusers',sep='|',header=None)

       0   1  2              3      4
0      1  24  M     technician  85711
1      2  53  F          other  94043
2      3  23  M         writer  32067
3      4  24  M     technician  43537
4      5  33  F          other  15213
5      6  42  M      executive  98101
6      7  57  M  administrator  91344
7      8  36  M  administrator  05201
8      9  29  M        student  01002
9     10  53  M         lawyer  90703
10    11  39  F          other  30329
11    12  28  F          other  06405
12    13  47  M       educator  29206
13    14  45  M      scientist  55106
14    15  49  F       educator  97301
15    16  21  M  entertainment  10309
16    17  30  M     programmer  06355
17    18  35  F          other  37212
18    19  40  M      librarian  02138
19    20  42  F      homemaker  95660
20    21  26  M         writer  30068
21    22  25  M         writer  40206
22    23  30  F         artist  48197
23    24  21  F         artist  94533
24    25  39  M       engineer  55107
25    26  49  M       engineer  21044
26    27  40  F      librarian  30030
27    28  32  M         writer  55369
28    29  41  M     programmer  94043
29    30   7  M        student  55436
..   ...  .. ..            ...    ...
913  914  44  F          other  08105
914  915  50  M  entertainment  60614
915  916  27  M       engineer  N2L5N
916  917  22  F        student  20006
917  918  40  M      scientist  70116
918  919  25  M          other  14216
919  920  30  F         artist  90008
920  921  20  F        student  98801
921  922  29  F  administrator  21114
922  923  21  M        student  E2E3R
923  924  29  M          other  11753
924  925  18  F       salesman  49036
925  926  49  M  entertainment  01701
926  927  23  M     programmer  55428
927  928  21  M        student  55408
928  929  44  M      scientist  53711
929  930  28  F      scientist  07310
930  931  60  M       educator  33556
931  932  58  M       educator  06437
932  933  28  M        student  48105
933  934  61  M       engineer  22902
934  935  42  M         doctor  66221
935  936  24  M          other  32789
936  937  48  M       educator  98072
937  938  38  F     technician  55038
938  939  26  F        student  33319
939  940  32  M  administrator  02215
940  941  20  M        student  97229
941  942  48  F      librarian  78209
942  943  22  M        student  77841

[943 rows x 5 columns]

In [9]:
user_cols = ['users_id','age','gender','occupation','zip_code']
users = pd.read_table('http://bit.ly/movieusers',sep='|',header=None,names=user_cols)

     users_id  age gender     occupation zip_code
0           1   24      M     technician    85711
1           2   53      F          other    94043
2           3   23      M         writer    32067
3           4   24      M     technician    43537
4           5   33      F          other    15213
5           6   42      M      executive    98101
6           7   57      M  administrator    91344
7           8   36      M  administrator    05201
8           9   29      M        student    01002
9          10   53      M         lawyer    90703
10         11   39      F          other    30329
11         12   28      F          other    06405
12         13   47      M       educator    29206
13         14   45      M      scientist    55106
14         15   49      F       educator    97301
15         16   21      M  entertainment    10309
16         17   30      M     programmer    06355
17         18   35      F          other    37212
18         19   40      M      librarian    02138
19         20   42      F      homemaker    95660
20         21   26      M         writer    30068
21         22   25      M         writer    40206
22         23   30      F         artist    48197
23         24   21      F         artist    94533
24         25   39      M       engineer    55107
25         26   49      M       engineer    21044
26         27   40      F      librarian    30030
27         28   32      M         writer    55369
28         29   41      M     programmer    94043
29         30    7      M        student    55436
..        ...  ...    ...            ...      ...
913       914   44      F          other    08105
914       915   50      M  entertainment    60614
915       916   27      M       engineer    N2L5N
916       917   22      F        student    20006
917       918   40      M      scientist    70116
918       919   25      M          other    14216
919       920   30      F         artist    90008
920       921   20      F        student    98801
921       922   29      F  administrator    21114
922       923   21      M        student    E2E3R
923       924   29      M          other    11753
924       925   18      F       salesman    49036
925       926   49      M  entertainment    01701
926       927   23      M     programmer    55428
927       928   21      M        student    55408
928       929   44      M      scientist    53711
929       930   28      F      scientist    07310
930       931   60      M       educator    33556
931       932   58      M       educator    06437
932       933   28      M        student    48105
933       934   61      M       engineer    22902
934       935   42      M         doctor    66221
935       936   24      M          other    32789
936       937   48      M       educator    98072
937       938   38      F     technician    55038
938       939   26      F        student    33319
939       940   32      M  administrator    02215
940       941   20      M        student    97229
941       942   48      F      librarian    78209
942       943   22      M        student    77841

[943 rows x 5 columns]